<a href="https://ondiande.com/contact/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="ONDIA Contact" width="110" height="200" title="This notebook is licensed by ONDIA. Please contact the authorized persons about the conditions under which you can use or share."></a>

<div style="background-color:#8CCED1; font-family:newtimeroman; color:#635EA7; font-size:200%; text-align:center; border-radius:10px 10px; margin-top:20px; margin-bottom:20px; padding-top:15px; padding-bottom:15px; font-weight:bold;"></div>

<p style="text-align: center;"> <a href="https://ondiande.com/"> <img src="https://i.ibb.co/mvHRT4S/ONDIA-logo.png" width="500" height="200" class="img-fluid" alt="ONDIA LOGO" title="INTELLIGENT & PERSONALIZED SOLUTIONS TO DATA ANALYSIS AND DATA MANAGEMENT ISSUES"> </a> </p>

<div style="background-color:#58B8E4; font-family:newtimeroman; color:#635EA7; font-size:200%; text-align:center; border-radius:10px 10px; margin-top:20px; margin-bottom:20px; padding-top:15px; padding-bottom:15px; font-weight:bold;">
  Intelligent & Personalized Solutions
</div>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:300%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

<div style="background-color:#8CCED1; font-family:newtimeroman; color:#635EA7; font-size:200%; text-align:center; border-radius:10px 10px; margin-top:20px; margin-bottom:20px; padding-top:15px; padding-bottom:15px; font-weight:bold;"></div>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<div style="background-color:#58B8E4; font-family:newtimeroman; color:#635EA7; font-size:200%; text-align:center; border-radius:10px 10px; margin-top:20px; margin-bottom:20px; padding-top:15px; padding-bottom:15px; font-weight:bold;"></div>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [3]:
import numpy as np



### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [7]:
my_list = [5, 10, 15, 20, 25]
array = np.array(my_list)
array



array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros.

In [11]:
zeros_array = np.full((5, 5), 0)
zeros_array



array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [13]:
ones= np.ones((4, 4), dtype=int)
ones



array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [17]:
ones = np.ones((4, 4), dtype=int) * 7
ones


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [23]:
full_array = np.full((4, 4), 7)
full_array





array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive).

In [25]:
even_numbers = np.arange(2, 17, 2)
even_numbers



array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [27]:
matrix_5x5 = np.arange(0, 25).reshape(5, 5)
matrix_5x5




array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [33]:
matrix5x5_linspace = np.linspace(0, 24, 25, dtype=int).reshape(5, 5)
matrix5x5_linspace



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 10. Create randomly 5 numbers with numpy.

In [35]:
random_numbers = np.random.rand(5)
random_numbers



array([0.29335226, 0.11859334, 0.39157017, 0.0485956 , 0.15888916])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [37]:
matrix_ndistribution = np.random.randn(5, 5)
matrix_ndistribution



array([[-0.50757226,  1.36891045,  1.44702323, -0.35405004, -1.32745906],
       [-0.06678297,  0.96889211,  1.04503771,  0.34622836,  1.43505173],
       [ 1.15714288, -0.90580361, -0.31815869,  0.17974149, -1.19080042],
       [-0.82641403, -0.5492179 , -1.59122831,  1.00295883,  1.47951416],
       [ 0.05913307,  0.01452331,  1.19131402,  0.56748664, -0.21242339]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [41]:
matrix_random_ints = np.random.randint(20, 50, (3, 4))
matrix_random_ints



array([[36, 40, 33, 29],
       [20, 28, 28, 20],
       [28, 22, 40, 45]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [43]:
ranarr = np.random.randint(1, 100, 48)
ranarr



array([84, 65, 19, 69, 81,  1, 36,  5, 47, 27,  8, 37, 15,  3, 58, 89, 39,
       97, 98,  1, 78, 34, 33, 94, 95, 29, 24, 72, 19, 82, 70, 12, 24, 75,
       58, 70, 49, 66, 72, 22, 70, 57, 41, 21, 46, 51, 72, 42])

In [45]:
ranarr_reshaped = ranarr.reshape(6, 8)
ranarr_reshaped



array([[84, 65, 19, 69, 81,  1, 36,  5],
       [47, 27,  8, 37, 15,  3, 58, 89],
       [39, 97, 98,  1, 78, 34, 33, 94],
       [95, 29, 24, 72, 19, 82, 70, 12],
       [24, 75, 58, 70, 49, 66, 72, 22],
       [70, 57, 41, 21, 46, 51, 72, 42]])

In [47]:
ranarr_reshaped2 = ranarr.reshape(-1, 8)
ranarr_reshaped2



array([[84, 65, 19, 69, 81,  1, 36,  5],
       [47, 27,  8, 37, 15,  3, 58, 89],
       [39, 97, 98,  1, 78, 34, 33, 94],
       [95, 29, 24, 72, 19, 82, 70, 12],
       [24, 75, 58, 70, 49, 66, 72, 22],
       [70, 57, 41, 21, 46, 51, 72, 42]])

In [49]:
ranarr_reshaped3 = ranarr.reshape(6, -1)
ranarr_reshaped3



array([[84, 65, 19, 69, 81,  1, 36,  5],
       [47, 27,  8, 37, 15,  3, 58, 89],
       [39, 97, 98,  1, 78, 34, 33, 94],
       [95, 29, 24, 72, 19, 82, 70, 12],
       [24, 75, 58, 70, 49, 66, 72, 22],
       [70, 57, 41, 21, 46, 51, 72, 42]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [51]:
mat = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13,14, 15, 16]
])

mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [55]:
crop_matrix = mat[1:3, 1:3]
crop_matrix


array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [57]:
first_column = mat[:, 0]
first_column


array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [59]:
filtere_row = mat[1, ::2]
filtere_row


array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [63]:
mat[:, 2] = 77
mat


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [65]:
selected_values = np.array([mat[1, 0], mat[3, 2]])
selected_values


array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [67]:
sliced_mat = mat[1::2, ::2]
sliced_mat


array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [69]:
mat = np.array([
    [1,  2,  77,  4],
    [5,  6,  77,  8],
    [9, 10, 77, 12],
    [13, 14, 77, 16]
])

mat


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [71]:
values_smaller_10 = mat[mat < 10]
values_smaller_10



array([1, 2, 4, 5, 6, 8, 9])

In [75]:
values_bigger_12 = mat[mat > 12]
values_bigger_12



array([77, 77, 77, 13, 14, 77, 16])

In [89]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat"

# YOUR CODE IS HERE

sum = values_smaller_10 + values_bigger_12 
sum






array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [105]:
std_value = np.std(sum)

std_value




29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [113]:
# LET US REMEMBER OUR ARRAY OF "mat"

# YOUR CODE IS HERE
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [117]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat"

# YOUR CODE IS HERE

mat = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [119]:
# YOUR CODE IS HERE
sum_column_2 = np.sum(mat[:, 1])

sum_column_2



32

### 23. Get the median, mean and std of 3rd column in "mat".

In [151]:
# LET US REMEMBER OUR ARRAY OF "mat"

# YOUR CODE IS HERE

mat = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

mat




array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [149]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE

# YOUR CODE IS HERE

third_column = mat[:, 2].reshape(-1, 1)

third_column




array([[ 3],
       [ 7],
       [11],
       [15]])

In [147]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW?

# YOUR CODE IS HERE

third_row = mat[2, :]

third_row



array([ 9, 10, 11, 12])

In [157]:
# LET US GET MEDIAN VALUE

# YOUR CODE IS HERE
median_row = np.median(mat[2, :])
median_col = np.median(mat[:, 2])

print(median_col,median_row)





9.0 10.5


In [163]:
# LET US GET MEAN VALUE

# YOUR CODE IS HERE

mean_row = np.mean(mat[2, :])
mean_col = np.mean(mat[:, 2])

print(mean_col,mean_row)



9.0 10.5


In [165]:
# LET US GET STANDART DEVIATION (std) VALUE

# YOUR CODE IS HERE

std_row = np.std(mat[2, :])
std_col = np.std(mat[:, 2])

print(std_col,std_row)



4.47213595499958 1.118033988749895


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [170]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [172]:
# LET US READ Salaries.csv

# YOUR CODE IS HERE

df = pd.read_csv("Salaries.csv")



In [178]:
# LET US LOOK AT THE FIRST 5 ROWS

# YOUR CODE IS HERE
df.head()



Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [184]:
# LET US GET A SAMPLE

# YOUR CODE IS HERE
df.sample()



Id      EmployeeName                JobTitle  BasePay  \
105889  105890  Danielle A Lowen  Public Service Trainee  10321.5   

        OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
105889          0.0       0.0    103.22   10321.5          10424.72  2013   

        Notes         Agency  Status  
105889    NaN  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [182]:
# YOUR CODE IS HERE
df.info() 



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [180]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS

df.describe()



Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [186]:
# YOUR CODE IS HERE
year_counts = df["Year"].value_counts()
year_counts



Year
2014    38123
2013    37606
2012    36766
2011    36159
Name: count, dtype: int64

In [188]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

unique_year_count = df["Year"].nunique()
unique_year_count



4

In [190]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

unique_years = df["Year"].unique()
unique_years



array([2011, 2012, 2013, 2014])

### Print out max and avg values in the column of "Totalpay".

In [192]:
# LET US FIND THE MAXIMUM TOTALPAY

max_totalpay = df["TotalPay"].max()
max_totalpay




567595.43

In [200]:
# LET US FIND THE AVERAGE TOTALPAY

avg_totalpay = df["TotalPay"].mean()
avg_totalpay



74768.32197169267

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [219]:
# YOUR CODE IS HERE
filtered_df = df[df["TotalPay"] > avg_totalpay]
filtered_df


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [213]:
# YOUR CODE IS HERE

bigger_than_avg = (df["TotalPay"] > avg_totalpay).sum()

print(bigger_than_avg)

69489


### How much does ALBERT PARDINI make money (including benefits)?

In [221]:
# YOUR CODE IS HERE
pardini_salary = df[df["EmployeeName"] == "ALBERT PARDINI"]["TotalPayBenefits"]
pardini_salary 


2    335279.91
Name: TotalPayBenefits, dtype: float64

### Who is the lowest paid person?

In [223]:
# YOUR CODE IS HERE
lowest_paid = df.loc[df["TotalPay"].idxmin(), ["EmployeeName"]]
lowest_paid



EmployeeName    Joe Lopez
Name: 148653, dtype: object

### What are the unique Jobs in dataset?

In [225]:
# YOUR CODE IS HERE
unique_jobs = df["JobTitle"].unique()

unique_jobs


array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [ ]:
# YOUR CODE IS HERE# En az yaygın 3 iş pozisyonunu bulma



### How many people earned more than avg in 2012?

### How many people have a title of Manager in their jobs?

In [257]:
# USE APPLY FUNCTION

# YOUR CODE IS HERE
manager_count = df["JobTitle"].apply(lambda x: "manager" in x.lower()).sum()

manager_count


4110


### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [247]:
# YOUR CODE IS HERE
sal_new = df.iloc[:, [0, 1, 2, 7, 8]]
sal_new



Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [255]:
# YOUR CODE IS HERE
sal_new_df = df.loc[:, ["EmployeeName", "JobTitle", "TotalPay", "TotalPayBenefits"]]
sal_new_df



EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [259]:
min_salary = df["TotalPay"].min()
avg_salary = df["TotalPay"].mean()

filtered_employees = df[(df["TotalPay"] > min_salary) & (df["TotalPay"] < avg_salary)][["EmployeeName", "TotalPayBenefits"]]

print(filtered_employees)



             EmployeeName  TotalPayBenefits
15847   TATYANA ROTENBERG          74764.87
15848         WINSTON HOM          74761.55
15849        CRAIG RIGLER          74759.92
15850           WENDY TAN          74756.76
15851      KENNETH BREWER          74751.59
...                   ...               ...
148648        Leon Walker              0.00
148649      Roy I Tillery              0.00
148650       Not provided              0.00
148651       Not provided              0.00
148652       Not provided              0.00

[79164 rows x 2 columns]


Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<hr>

<p style="background-color:#FDFEFE; font-family:newtimeroman; color:#635EA7; font-size:350%; text-align:center; border-radius:10px 10px;">End of The Assignment - 1</p>

# <span style="color:#DA55E5">**Now. it's time to relax!**<span>
    
![Image_Assignment](https://i.ibb.co/jZD3Mqb/relaxing.jpg)
   

<a href="https://ondiande.com/contact/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="ONDIA Contact" width="110" height="200" title="This notebook is licensed by ONDIA. Please contact the authorized persons about the conditions under which you can use or share."></a>